### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by carlocorradini** [karljj1/kdis#25]
@karljj1 Can you create an account on [Codecov](https://codecov.io) for `kdis`

Thanks 🥳🤗

**Comment by karljj1** [comment]
Its setup. I added the secret, you just need to put it into the actions somewhere:

```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
